export const CHOOSE_CITY = "CHOOSE_CITY";
export const GET_WEATHER_DATA = "GET_WEATHER_DATA";
export const GET_LIST_CITY = "GET_LIST_CITY";
export const SEARCH_KEYWORD = "SEARCH_KEYWORD";
export const AUTO_REFRESH = "AUTO_REFRESH";
